### ISSUE TITLE
Predefinisani projekat za ocenu 7-8

### ISSUE THREAD

**Issue by OneZeroBeatz** [ftn-ai-lab/sc-2016-e2#101]
Student : Saša Momčilović
Broj indeksa : RA 201/2013
Asistent : @miroslavkondic 
Repozitorijum : https://github.com/OneZeroBeatz/softComputing
Podaci: https://drive.google.com/drive/folders/0B1ZJXQY32LBUMWdxWkEzcmVYblU

* Video zapis poseduje jednu pokretnu liniju koja je uvek iste boje. Liniju detektovati korišćenjem Hough transformacije
* Cifre se kreću za slučajan broj koraka i prolaze iza pokretne linije
* Potrebno je izvršiti sabiranje svih cifara koje prođu ispod linije
* Potrebno je postići tačnost prepoznavanja od bar 90%.

**Comment by miroslavftn** [comment]
Niste ispostovali pravila prijave projekta!

**Comment by OneZeroBeatz** [comment]
Je l sad bolje?

**Comment by miroslavftn** [comment]
Jeste
