### ISSUE TITLE
Generisanje skupa šema relacija i skupa međurelacionih ograničenja metodom sinteze

### ISSUE THREAD

**Issue by babycatatonia** [ftn-ai-lab/sc-2016-e2#13]
Clanovi: Stefan Bubanj RA166/2013 i Sasa Momcilovic RA201/2013, grupa 2

- Opis: Na papiru se nalaze funkcionalne zavisnosti i skup obelezja. Aplikacija prepoznaje, posto ucitamo sliku, obelezja i zavisnosti i daje resenje u vidu skupa sema relacija postujuci sve korake metode sinteze.

- Algoritmi: Osnovne morfoloske transformacije nad slikom, neuronska mreza za prepoznavanje slova i specijalnih znakova.

- Validacija na osnovu resenja zadataka sa vezbi iz predmeta Baze podataka 2.

**Comment by miroslavftn** [comment]
Nedostaje link ka github repozitorijumu. Koje još algoritme iz computer vision-a planirate da koristite?

**Comment by babycatatonia** [comment]
https://github.com/babycatatonia/soft_sinteza
Naveli smo vam otprilike sta cemo koristiti, videcemo jos u hodu, nismo ni mi sigurni.
