### ISSUE TITLE
Prepoznavanje ER modela

### ISSUE THREAD

**Issue by SasaBoros** [ftn-ai-lab/sc-2016-e2#15]
**Članovi tima:** Milenko Simikić (RA62-2013), Goran Divović (RA214-2013) i Saša Boroš (RA69-2013). Grupa 6.

**Problem:** Prepoznavanje ER modela podrazumeva prepoznavanje elemenata modela (tipova entiteta, poveznika...) kao i naziva svakog elementa, a zatim adekvatan ispis dobijenih rezultata.

**Algoritmi:** Morfoloske transformacije nad slikom(+Hough), neuronska mreža za prepoznavanje karaktera.

**Metrika:** Metrika za poređenje performansi i/ili parametara: procenat uspešno prepoznatih elemenata/procenat uspešno prepoznatih karaktera.

**Podaci:** Samostalno kreirane slike uz pomoć adekvatnog programa(npr. paint), slike pronađene na internetu ili samostalno uslikane.

**Validacija:** Samostalno računanje tačnih rezulatata i poređenje sa dobijenim rezultatima.

**Repozitorijum:** https://github.com/SasaBoros/soft-2016

**Comment by StefanAndjelic** [comment]
Potrebno je postaviti link ka git repozitorijumu koji nameravate da koristite.

**Comment by SasaBoros** [comment]
Link je upravo postavljen.
